### PR TITLE
More 'project rules'

### PR DESCRIPTION
**Pull request by court-jus**
l10n is important

### CODE REVIEW

**Comment by andymeneely** [comment]
Internationalization is definitely important, but instead of making a rule about it let's actually just internationalize it.

**Comment by court-jus** [comment]
I've started some work on that :-) What I don't know is how to launch deck.rb with options

**Comment by andymeneely** [comment]
Ah. That's an interesting challenge I haven't worked on before. Let's do this: work on translation of what's needed an put them into a new `i18n` folder in just text files. I'll work on ways of creating builds for it. It might be a matter of translating it in Excel in separate columns - we'll see.

**Comment by court-jus** [comment]
What I imagined was to have a different XLS file (one per language) so we just have to open the right file into deck.rb

**Comment by andymeneely** [comment]
But then that's like maintaining different games altogether, and we'd have to keep them in sync. We could also have separate language files that the spreadsheet refers to. That keeps the math in one place and the natural language stuff in separate text files.

**Comment by andymeneely** [comment]
Excel also supports i18n too... https://docs.oracle.com/cd/E16162_01/web.1112/e16180/international_app.htm#ADFDI61648

Maybe that's the approach.

**Pull request closed without merging**
